(()=>{
'use strict';
const DEFAULTS=['ChatGPT','Netflix','Max / HBO Max','DIGI','Amazon Prime','Strava','Disney+'];
const KEY='family_subscriptions_v1';
const css=document.createElement('style');css.textContent=`
.subSummary{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-bottom:12px}.subMetric{background:#fff;border:1px solid var(--line);border-radius:13px;padding:12px}.subMetric small{display:block;color:var(--mut);font-size:10px;font-weight:800}.subMetric b{display:block;font-size:18px;margin-top:4px}.subList{display:grid;gap:8px}.subCard{background:#fff;border:1px solid var(--line);border-radius:13px;padding:12px}.subTop{display:flex;justify-content:space-between;gap:8px;align-items:center}.subTop b{font-size:15px}.subFields{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin-top:10px}.subFields .wide{grid-column:1/-1}.subActions{display:flex;gap:7px;margin-top:10px}.subHint{font-size:11px;color:var(--mut);margin:0 0 12px}.subEmpty{color:var(--mut);font-size:12px}.subDue{font-size:10px;color:var(--mut)}@media(max-width:700px){.subSummary{grid-template-columns:1fr}.subFields{grid-template-columns:1fr}.subFields .wide{grid-column:auto}}
`;document.head.appendChild(css);
function load(){try{let x=JSON.parse(localStorage.getItem(KEY)||'null');if(Array.isArray(x))return x}catch(e){}return DEFAULTS.map((name,i)=>({id:'sub-'+(i+1),name,price:'',period:'',payment:'',renewal:'',commitment:'',cancelBy:'',notes:''}))}
let items=load();
function save(){localStorage.setItem(KEY,JSON.stringify(items))}
function money(v){let n=Number(String(v||'').replace(',','.'));return Number.isFinite(n)?n:0}
function annual(x){let p=money(x.price);return x.period==='Mensual'?p*12:x.period==='Trimestral'?p*4:x.period==='Semestral'?p*2:x.period==='Anual'?p:0}
function euro(n){return n.toLocaleString('es-ES',{style:'currency',currency:'EUR'})}
function ensure(){let main=document.querySelector('main');if(!main||document.getElementById('subscriptions'))return;let s=document.createElement('section');s.id='subscriptions';s.className='view';s.innerHTML='<div class="ey">Gestión familiar</div><div class="title">Suscripciones</div><p class="subHint">Completa los datos cuando los tengas. Todo lo que falta queda editable.</p><div id="subBody"></div>';main.appendChild(s);render()}
function field(x,key,label,type='text',options){let val=x[key]||'';if(options)return `<div class="field"><label>${label}</label><select data-sub="${x.id}" data-key="${key}"><option value="">Sin indicar</option>${options.map(o=>`<option ${val===o?'selected':''}>${o}</option>`).join('')}</select></div>`;return `<div class="field"><label>${label}</label><input type="${type}" value="${String(val).replace(/"/g,'&quot;')}" data-sub="${x.id}" data-key="${key}"></div>`}
function render(){let body=document.getElementById('subBody');if(!body)return;let total=items.reduce((a,x)=>a+annual(x),0),monthly=total/12,now=new Date(),limit=new Date(now);limit.setDate(limit.getDate()+60);let due=items.filter(x=>x.renewal&&new Date(x.renewal+'T12:00:00')>=now&&new Date(x.renewal+'T12:00:00')<=limit).length;body.innerHTML=`<div class="subSummary"><div class="subMetric"><small>Coste mensual equivalente</small><b>${euro(monthly)}</b></div><div class="subMetric"><small>Coste anual conocido</small><b>${euro(total)}</b></div><div class="subMetric"><small>Renovaciones próximos 60 días</small><b>${due}</b></div></div><div class="subList">${items.map(x=>`<div class="subCard"><div class="subTop"><b>${x.name}</b><span class="subDue">${x.renewal?'Renueva '+new Date(x.renewal+'T12:00:00').toLocaleDateString('es-ES'):'Renovación sin indicar'}</span></div><div class="subFields">${field(x,'name','Servicio')}${field(x,'price','Precio (€)','number')}${field(x,'period','Periodicidad','text',['Mensual','Trimestral','Semestral','Anual','Otra'])}${field(x,'payment','Medio de pago')}${field(x,'renewal','Próxima renovación','date')}${field(x,'commitment','Permanencia / condiciones')}${field(x,'cancelBy','Fecha límite para cancelar','date')}<div class="wide">${field(x,'notes','Notas')}</div></div><div class="subActions"><button type="button" class="secondary danger" data-del-sub="${x.id}">Eliminar</button></div></div>`).join('')}</div><button type="button" id="addSubscription" class="primary" style="margin-top:12px">＋ Añadir suscripción</button>`;body.querySelectorAll('[data-sub]').forEach(el=>el.onchange=()=>{let x=items.find(a=>a.id===el.dataset.sub);if(x){x[el.dataset.key]=el.value;save();render()}});body.querySelectorAll('[data-del-sub]').forEach(b=>b.onclick=()=>{items=items.filter(x=>x.id!==b.dataset.delSub);save();render()});document.getElementById('addSubscription').onclick=()=>{items.push({id:'sub-'+Date.now(),name:'Nueva suscripción',price:'',period:'',payment:'',renewal:'',commitment:'',cancelBy:'',notes:''});save();render()}}
ensure();new MutationObserver(ensure).observe(document.querySelector('main'),{childList:true});window.familySubscriptionsRefresh=render;
})();