(()=>{
'use strict';
const KEY='family_weekly_auto_seen';
function iso2(d){return typeof iso==='function'?iso(d):d.toISOString().slice(0,10)}
function monday(d){const x=new Date(d);x.setHours(12,0,0,0);const day=x.getDay()||7;x.setDate(x.getDate()-day+1);return x}
function add(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x}
function nextWeek(){const start=add(monday(new Date()),7),days=[];for(let i=0;i<7;i++){const d=add(start,i),ds=iso2(d),items=[];(D.events||[]).filter(x=>x.event_date===ds).forEach(x=>items.push(x.title));try{rf(d).forEach(x=>items.push(x.title))}catch(e){}try{const s=schoolMarker(d);if(s)items.push('Ikastola: '+schoolText(s))}catch(e){}days.push({d,ds,items:[...new Set(items)]})}return {start,days,total:days.reduce((a,x)=>a+x.items.length,0)}}
function isTime(){const n=new Date();return n.getDay()===0&&n.getHours()>=16}
async function maybeNotify(info){if(!isTime()||localStorage.getItem(KEY)===info.days[0].ds)return;if(typeof notificationEnabled!=='function'||!notificationEnabled()||!('Notification' in window)||Notification.permission!=='granted')return;try{const reg=typeof notificationRegistration==='function'?await notificationRegistration():null;if(reg){await reg.showNotification('Planificación de la próxima semana',{body:`${info.total} acontecimientos previstos. Toca para revisar la semana.`,icon:'assets/app-icon-192.png',badge:'assets/app-icon-192.png',tag:'family-weekly-summary',data:{url:'./'}});localStorage.setItem(KEY,info.days[0].ds)}}catch(e){}}
function render(){const old=document.getElementById('weeklyAutoPreview');old?.remove();if(!isTime())return;const dash=document.getElementById('homeDashboard');if(!dash)return;const info=nextWeek(),card=document.createElement('button');card.id='weeklyAutoPreview';card.type='button';card.style.cssText='width:100%;text-align:left;border:1px solid #bfdbfe;background:#eff6ff;border-radius:14px;padding:12px;margin:0 0 12px';card.innerHTML=`<div style="font-size:10px;font-weight:900;color:#1d4ed8">🗓️ RESUMEN AUTOMÁTICO · PRÓXIMA SEMANA</div><div style="font-size:16px;font-weight:900;margin-top:4px">${info.total} acontecimiento${info.total===1?'':'s'} previstos</div><div style="font-size:11px;color:#64748b;margin-top:3px">Toca para ver la planificación completa de lunes a domingo.</div>`;const tools=dash.querySelector('.smartTopTools');(tools||dash.querySelector('.homeWelcome'))?.after(card);card.onclick=()=>window.familyOpenWeekly?.();maybeNotify(info)}
document.addEventListener('family-upcoming-rendered',()=>setTimeout(render,50));setTimeout(render,500);window.familyWeeklyAutoRefresh=render;
})();
